### ISSUE TITLE
Is android build possible?

### ISSUE THREAD

**Issue by schleicher** [AlbrechtL/rtl_fm_streamer#3]
I.e as app with built-in server via JNI?

**Comment by AlbrechtL** [comment]
Technically it should be possible. But what is your use case? There are already Android apps for SDR FM demodulating.

**Comment by LeoSchleicher** [comment]
I haven't found any app that can stream demodulated audio via http. They all try to play sounds via speaker/headphones. But I have special case - to use android smartphone as car entertainment system. I use USB Player Pro to stream music via external usb sound cart and car amplifier. 3.5 mm jack cannot deliver acceptable sound quality.
Now I want to stream dab/fm radio same way through USB Player App. This App can play audio from http. Hope that USB bandwidth is enough to receive radiosrteam and send audiodata simultaneously.

**Comment by AlbrechtL** [comment]
Thanks! Because this project is quite in a deep sleep mode I will close this issue for now.
