### ISSUE TITLE
Questions about HD Radio and RDS

### ISSUE THREAD

**Issue by heavyinfo** [AlbrechtL/rtl_fm_streamer#8]
First of all congratulations to @AlbrechtL for building a very successful tool which has been a staple for RTL_SDR community for getting high quality stereo FM audio.

I have two questions,

1. I'm able to decode successfully HD FM radio signal at 93500000 Hertz successfully using RTL2838UHIDIR DAB-T dongle with good quality audio playback, but non-HD radio stations are full of noise and unusable; frequencies being 98300000 Hertz, 106400000 Hertz, 91100000 Hertz etc. Am I missing something which prevents the decoding for non - HD signal properly?

2.Would it be possible to get RDS data (e.g. Song info) may be via JSON RPC?

**Comment by AlbrechtL** [comment]
to 1. I don't live inside the US. So I can't say anything to HD Radio.
to 2. Please try to use https://github.com/JvanKatwijk/wfm-rpi. It has a RDS decoder.
